version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: skill_lobang
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skill-lobang-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - skill-lobang-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/skill_lobang
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-here
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - skill-lobang-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - skill-lobang-network

volumes:
  postgres_data:

networks:
  skill-lobang-network:
    driver: bridge